[package]
name = "xdp-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
rand = "0.8"
socket2 = "0.5"
libc = "0.2"
